#!/usr/bin/env python3
"""Emit the events-catalog import as idempotent upsert SQL, merge-aware.

Reads the SOURCE catalog CSVs (data/events/v0.3/{series,editions,results}.csv) and the
reconciliation output (data/events/review/reconciliation.csv), applies the same mapping
as scripts/build-events-import.py PLUS the human-confirmed clean-merge decisions, and
writes SQL to data/events/v0.3/import/sql/.

Clean-merge decisions (see features/events-catalog-import-brief.md Step 2, confirmed in
the import session):
  - Two catalog series already exist in prod. Do NOT import a duplicate series; fold their
    editions into the existing series id.
        mt-baker-legendary-banked-slalom  -> es1                      (Baker Banked Slalom)
        westbeach-classic                 -> series_1774838253156_mep0c (Westbeach Classic)
  - 16 catalog editions duplicate an existing prod event (from reconciliation MATCH+FUZZY).
    Do NOT insert a duplicate event row. Re-point that edition's podium results onto the
    existing event id, so the real row (e.g. the landing-page 2019 Baker) gains its podium.

READ ONLY with respect to the database. Writes SQL files and nothing else.

Usage:
  python3 scripts/reconcile-events.py     # first, produces reconciliation.csv
  python3 scripts/build-events-sql.py
"""
import csv, json, os, re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data/events/v0.3"
RECON = ROOT / "data/events/review/reconciliation.csv"
OUT = SRC / "import/sql"
OUT.mkdir(parents=True, exist_ok=True)

# Catalog series that already exist in prod under a different id. Their editions fold into
# the existing series; the catalog series row itself is not imported.
SERIES_REMAP = {
    "mt-baker-legendary-banked-slalom": "es1",
    "westbeach-classic": "series_1774838253156_mep0c",
}
FREQ = {"tour-series": "tour", "tour-stop": "annual", "major-contest": "annual",
        "legacy-contest": "annual", "grassroots-contest": "annual",
        "national-championship": "annual"}

# Editions the contest was scheduled for but never actually held are excluded from the
# import: they are phantom years that inflate the events list (e.g. the Mt Baker LBS was
# postponed in 2021/2022/2024/2026, and 2027 is not yet held). This overrides the brief's
# DECISION 5 per Jay 2026-09-07. These rows carry no podiums, so nothing is orphaned.
SKIP_STATUSES = {"cancelled", "unconfirmed", "postponed"}


def rows(p):
    with open(SRC / p, newline="") as fh:
        return list(csv.DictReader(fh))


def pipe(v):
    return [x.strip() for x in (v or "").split("|") if x.strip()]


# ── SQL literal helpers ──────────────────────────────────────────────────────
def q(v):
    """A scalar SQL literal. Empty/None -> NULL. Everything else single-quoted, escaped."""
    if v is None or v == "":
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def qi(v):
    return "NULL" if v in (None, "") else str(int(v))


def qarr(v, not_null=False):
    """text[] literal from a pipe-delimited string, via ARRAY[...] to sidestep array-literal
    escaping. Empty -> '{}'::text[] when the column is NOT NULL, else NULL."""
    items = pipe(v)
    if not items:
        return "'{}'::text[]" if not_null else "NULL"
    return "ARRAY[" + ",".join("'" + i.replace("'", "''") + "'" for i in items) + "]::text[]"


# ── JSON (PostgREST) value helpers: the same shape, typed for a JSON body ──────
def jval(v):
    return None if v in (None, "") else v


def jint(v):
    return None if v in (None, "") else int(v)


def jarr(v, not_null=False):
    items = pipe(v)
    return items if items else ([] if not_null else None)


# ── Load the reconciliation: catalog_slug -> existing_id for the 16 collisions ──
collide_to_existing = {}
for r in csv.DictReader(open(RECON)):
    if r["bucket"] in ("MATCH", "FUZZY") and r["catalog_slug"]:
        collide_to_existing[r["catalog_slug"]] = r["existing_id"]

series_in = rows("series.csv")
editions_in = rows("editions.csv")
results_in = rows("results.csv")


def batched_insert(path, table, cols, values, conflict, update_cols):
    """Write one file of multi-row INSERT ... ON CONFLICT DO UPDATE statements, batched."""
    BATCH = 200
    set_clause = ", ".join(f"{c}=EXCLUDED.{c}" for c in update_cols)
    with open(path, "w") as fh:
        fh.write(f"-- {table}: {len(values)} rows, upsert (idempotent). Generated by build-events-sql.py\n")
        for i in range(0, len(values), BATCH):
            chunk = values[i:i + BATCH]
            fh.write(f"insert into public.{table} ({', '.join(cols)}) values\n")
            fh.write(",\n".join("  (" + ", ".join(row) + ")" for row in chunk))
            fh.write(f"\non conflict {conflict} do update set {set_clause};\n")
    return len(values)


# ── event_series ─────────────────────────────────────────────────────────────
series_cols = ["id", "name", "frequency", "start_year", "end_year", "description",
               "catalog_category", "catalog_status", "governing_body", "region",
               "home_venue", "country", "former_names", "disciplines", "sources", "confidence"]
series_vals, series_json = [], []
skipped_series = 0
for s in series_in:
    if s["series_id"] in SERIES_REMAP:
        skipped_series += 1
        continue
    series_vals.append([
        q(s["series_id"]), q(s["series_name"]), q(FREQ.get(s["category"], "irregular")),
        qi(s["first_year"]), qi(s["last_year"]), q(s["significance"]),
        q(s["category"]), q(s["status"]), q(s["governing_body"]), q(s["region"]),
        q(s["home_venue"]), q(s["country"]), qarr(s["former_names"]), qarr(s["disciplines"]),
        qarr(s["sources"]), q(s["confidence"]),
    ])
    series_json.append({
        "id": s["series_id"], "name": s["series_name"],
        "frequency": FREQ.get(s["category"], "irregular"),
        "start_year": jint(s["first_year"]), "end_year": jint(s["last_year"]),
        "description": jval(s["significance"]), "catalog_category": jval(s["category"]),
        "catalog_status": jval(s["status"]), "governing_body": jval(s["governing_body"]),
        "region": jval(s["region"]), "home_venue": jval(s["home_venue"]),
        "country": jval(s["country"]), "former_names": jarr(s["former_names"]),
        "disciplines": jarr(s["disciplines"]), "sources": jarr(s["sources"]),
        "confidence": jval(s["confidence"]),
    })
n_series = batched_insert(OUT / "01_series.sql", "event_series", series_cols, series_vals,
                          "(id)", [c for c in series_cols if c != "id"])

# ── events ───────────────────────────────────────────────────────────────────
events_cols = ["id", "external_ref", "name", "series_id", "year", "start_date", "end_date",
               "event_type", "description", "community_status", "catalog_status",
               "catalog_status_note", "date_precision", "venue_name", "city", "country",
               "disciplines", "sources", "confidence"]
events_vals, events_json = [], []
skipped_editions = 0
skipped_neverheld = set()
for e in editions_in:
    if e["edition_id"] in collide_to_existing:
        skipped_editions += 1
        continue
    if e["status"] in SKIP_STATUSES:
        skipped_neverheld.add(e["edition_id"])
        continue
    sd = e["start_date"] or str(e["year"])
    dp = ("day" if len(sd) == 10 else "month" if len(sd) == 7 else "year" if len(sd) == 4 else None)
    series_id = SERIES_REMAP.get(e["series_id"], e["series_id"])
    # Mt Baker LBS uses a consistent "[YEAR] Mt. Baker Legendary Banked Slalom" name
    # (per Jay 2026-09-07) rather than the mixed catalog edition_labels ("30th ...").
    if e["series_id"] == "mt-baker-legendary-banked-slalom":
        name = f'{e["year"]} Mt. Baker Legendary Banked Slalom'
    else:
        name = e["edition_label"] or f'{e["year"]} {e["series_id"]}'
    cstatus = "verified" if e["confidence"] == "verified" else "unverified"
    events_vals.append([
        q(e["edition_id"]), q(e["edition_id"]), q(name),
        q(series_id), qi(e["year"]), q(sd), q(e["end_date"]),
        q("contest"), q(e["notes"]), q(cstatus),
        q(e["status"]), q(e["status_note"]), q(dp),
        q(e["venue"]), q(e["city"]), q(e["country"]),
        qarr(e["disciplines"]), qarr(e["sources"]), q(e["confidence"]),
    ])
    events_json.append({
        "id": e["edition_id"], "external_ref": e["edition_id"], "name": name,
        "series_id": series_id, "year": jint(e["year"]), "start_date": sd,
        "end_date": jval(e["end_date"]), "event_type": "contest",
        "description": jval(e["notes"]), "community_status": cstatus,
        "catalog_status": jval(e["status"]), "catalog_status_note": jval(e["status_note"]),
        "date_precision": dp, "venue_name": jval(e["venue"]), "city": jval(e["city"]),
        "country": jval(e["country"]), "disciplines": jarr(e["disciplines"]),
        "sources": jarr(e["sources"]), "confidence": jval(e["confidence"]),
    })
n_events = batched_insert(OUT / "02_events.sql", "events", events_cols, events_vals,
                          "(id)", [c for c in events_cols if c != "id"])

# ── event_results ────────────────────────────────────────────────────────────
results_cols = ["event_id", "discipline", "division_label", "division_gender", "division_class",
                "division_age_band", "event_name", "place", "rider_name", "nationality",
                "score_or_time", "notes", "sources", "confidence", "citation_status"]
results_vals, results_json = [], []
repointed = 0
for r in results_in:
    if r["edition_id"] in skipped_neverheld:
        continue  # its edition was not imported (never held); no podium exists anyway
    ev_id = collide_to_existing.get(r["edition_id"], r["edition_id"])
    if r["edition_id"] in collide_to_existing:
        repointed += 1
    results_vals.append([
        q(ev_id), q(r["discipline"]), q(r["division_label"]), q(r["division_gender"]),
        q(r["division_class"]), q(r["division_age_band"]), q(r["event_name"]),
        str(int(r["place"])), q(r["rider_name"]), q(r["nationality"]),
        q(r["score_or_time"]), q(r["notes"]), qarr(r["sources"], not_null=True),
        q(r["confidence"] or "likely"), q(r["citation_status"]),
    ])
    results_json.append({
        "event_id": ev_id, "discipline": r["discipline"],
        "division_label": jval(r["division_label"]), "division_gender": jval(r["division_gender"]),
        "division_class": jval(r["division_class"]), "division_age_band": jval(r["division_age_band"]),
        "event_name": jval(r["event_name"]), "place": int(r["place"]),
        "rider_name": r["rider_name"], "nationality": jval(r["nationality"]),
        "score_or_time": jval(r["score_or_time"]), "notes": jval(r["notes"]),
        "sources": jarr(r["sources"], not_null=True), "confidence": r["confidence"] or "likely",
        "citation_status": jval(r["citation_status"]),
    })
# results split into several files so each stays a comfortable size for one MCP call
n_results = batched_insert(OUT / "03_results.sql", "event_results", results_cols, results_vals,
                           "on constraint event_results_slot_uniq",
                           [c for c in results_cols if c != "event_id"])

# JSON bodies for the PostgREST uploader (scripts/upload-events.mjs)
json.dump(series_json, open(OUT / "series.json", "w"))
json.dump(events_json, open(OUT / "events.json", "w"))
json.dump(results_json, open(OUT / "results.json", "w"))

print(f"series:  {n_series} inserted ({skipped_series} skipped, already in prod)")
print(f"events:  {n_events} inserted ({skipped_editions} merged into existing rows, "
      f"{len(skipped_neverheld)} skipped as never-held)")
print(f"results: {n_results} inserted ({repointed} re-pointed onto existing events)")
print(f"wrote {OUT}/  (both .sql and .json)")
