#!/usr/bin/env python3
"""Turn the events catalog CSVs into an idempotent seed.sql.

Usage:  python3 build_seed.py [catalog_dir] [out.sql]
Default: the directory this script's parent sits in, and events_seed.sql beside it.

Every statement is INSERT ... ON CONFLICT DO UPDATE, so the file can be run repeatedly.
Re-running after a catalog refresh updates changed rows and leaves member data untouched.
Rows are never deleted by this script; removals are a deliberate, separate decision.
"""
import csv,sys,os

HERE=os.path.dirname(os.path.abspath(__file__))
SRC=sys.argv[1] if len(sys.argv)>1 else os.path.dirname(HERE)
OUT=sys.argv[2] if len(sys.argv)>2 else os.path.join(HERE,'events_seed.sql')

def q(v):
    if v is None or v=='': return 'null'
    return "'"+str(v).replace("'","''")+"'"
def qi(v):
    if v is None or str(v).strip()=='': return 'null'
    try: return str(int(float(v)))
    except ValueError: return 'null'
def qd(v):
    """Dates arrive at three precisions. Rather than drop the coarse ones, widen them to the first
    of the month or the year and record the precision, so nothing is silently lost or overstated."""
    v=(v or '').strip()
    if not v: return 'null','null'
    if len(v)==10: return q(v),q('day')
    if len(v)==7:  return q(v+'-01'),q('month')
    if len(v)==4:  return q(v+'-01-01'),q('year')
    return 'null','null'
def qa(v):
    """Pipe-separated source list -> Postgres text[]."""
    v=(v or '').strip()
    if not v: return "'{}'::text[]"
    parts=[p.strip() for p in v.split('|') if p.strip()]
    return 'array['+','.join(q(p) for p in parts)+']::text[]' if parts else "'{}'::text[]"

def rows(name):
    with open(os.path.join(SRC,name),newline='') as fh:
        return list(csv.DictReader(fh))

out=[]
out.append("-- Generated by build_seed.py. Do not hand-edit; regenerate from the CSVs.\n")
out.append("begin;\n")

S=rows('series.csv')
out.append(f"\n-- {len(S)} series\n")
for r in S:
    out.append("insert into public.event_series (series_id,series_name,former_names,category,governing_body,"
      "first_year,last_year,status,home_venue,country,region,disciplines,significance,sources,confidence) values ("
      f"{q(r['series_id'])},{q(r['series_name'])},{qa(r['former_names'])},{q(r['category'])},{q(r['governing_body'])},"
      f"{qi(r['first_year'])},{qi(r['last_year'])},{q(r['status'])},{q(r['home_venue'])},{q(r['country'])},"
      f"{q(r['region'])},{qa(r['disciplines'])},{q(r['significance'])},{qa(r['sources'])},{q(r['confidence'])})\n"
      "on conflict (series_id) do update set series_name=excluded.series_name,former_names=excluded.former_names,"
      "category=excluded.category,governing_body=excluded.governing_body,first_year=excluded.first_year,"
      "last_year=excluded.last_year,status=excluded.status,home_venue=excluded.home_venue,country=excluded.country,"
      "region=excluded.region,disciplines=excluded.disciplines,significance=excluded.significance,"
      "sources=excluded.sources,confidence=excluded.confidence,updated_at=now();\n")

E=rows('editions.csv')
out.append(f"\n-- {len(E)} editions\n")
for r in E:
    sd,sp=qd(r['start_date']); ed,ep=qd(r['end_date'])
    prec = sp if sp!='null' else ep
    out.append("insert into public.event_editions (edition_id,series_id,year,edition_label,start_date,end_date,"
      "date_precision,venue,city,country,disciplines,status,status_note,notes,sources,confidence) values ("
      f"{q(r['edition_id'])},{q(r['series_id'])},{qi(r['year'])},{q(r['edition_label'])},{sd},"
      f"{ed},{prec},{q(r['venue'])},{q(r['city'])},{q(r['country'])},{qa(r['disciplines'])},"
      f"{q(r['status'])},{q(r['status_note'])},{q(r['notes'])},{qa(r['sources'])},{q(r['confidence'])})\n"
      "on conflict (edition_id) do update set series_id=excluded.series_id,year=excluded.year,"
      "edition_label=excluded.edition_label,start_date=excluded.start_date,end_date=excluded.end_date,"
      "date_precision=excluded.date_precision,"
      "venue=excluded.venue,city=excluded.city,country=excluded.country,disciplines=excluded.disciplines,"
      "status=excluded.status,status_note=excluded.status_note,notes=excluded.notes,sources=excluded.sources,"
      "confidence=excluded.confidence,updated_at=now();\n")

R=rows('results.csv')
out.append(f"\n-- {len(R)} results\n")
for r in R:
    out.append("insert into public.event_results (edition_id,discipline,division,division_label,division_gender,"
      "division_class,division_age_band,event_name,place,rider_name,nationality,score_or_time,notes,sources,"
      "confidence,citation_status) values ("
      f"{q(r['edition_id'])},{q(r['discipline'])},{q(r['division'])},{q(r['division_label'])},"
      f"{q(r['division_gender'])},{q(r['division_class'])},{q(r['division_age_band'])},{q(r['event_name'])},"
      f"{qi(r['place'])},{q(r['rider_name'])},{q(r['nationality'])},{q(r['score_or_time'])},{q(r['notes'])},"
      f"{qa(r['sources'])},{q(r['confidence'])},{q(r['citation_status'])})\n"
      "on conflict on constraint event_results_slot_uniq do update set "
      "division=excluded.division,division_gender=excluded.division_gender,division_class=excluded.division_class,"
      "division_age_band=excluded.division_age_band,nationality=excluded.nationality,"
      "score_or_time=excluded.score_or_time,notes=excluded.notes,sources=excluded.sources,"
      "confidence=excluded.confidence,citation_status=excluded.citation_status;\n")

out.append("\ncommit;\n")
with open(OUT,'w') as fh: fh.write("".join(out))
print(f"{OUT}: {len(S)} series, {len(E)} editions, {len(R)} results, {os.path.getsize(OUT)/1e6:.1f} MB")
